<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="assets/style.css" />
    </head>
    <body>
        <header>
            <h1>Projet soutien authentification</h1>
        </header>
        <?php

        if($route === "profile")
        {
            require "templates/profile.phtml";
        }
        else if($route === "admin")
        {
            require "templates/admin.phtml";
        }
        else
        {
            require "templates/home.phtml";
        }

        ?>
        <footer>
            <p>
                Projet de soutien sur l'authentification en PHP : session BRE01.
            </p>
        </footer>
    </body>
</html>